// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"pyramid/pyramid-manage/backend/app/backend/internal/biz"
	"pyramid/pyramid-manage/backend/app/backend/internal/conf"
	"pyramid/pyramid-manage/backend/app/backend/internal/data"
	"pyramid/pyramid-manage/backend/app/backend/internal/server"
	"pyramid/pyramid-manage/backend/app/backend/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUseCase := biz.NewGreeterUseCase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUseCase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	sysChainUseCase := biz.NewSysChainUseCase()
	pyramidService := service.NewPyramidService(sysChainUseCase)
	httpServer := server.NewHTTPServer(confServer, greeterService, pyramidService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
